
_isOfficer = (_type == "CO")||(_type == "B_Officer_F")||(_type == "O_Officer_F");
_isSquadLeader = (_type == "SL")||(_type == "B_Soldier_SL_F")||(_type == "O_Soldier_SL_F");
_isTeamLeader = (_type == "FTL")||(_type == "B_Soldier_TL_F")||(_type == "O_Soldier_TL_F");
_isRifleman = (_type == "rifleman")||(_type == "B_Soldier_F")||(_type == "O_Soldier_F");
_isRiflemanAT = (_type == "at")||(_type == "B_Soldier_LAT_F")||(_type == "O_Soldier_LAT_F");
_isMarksman = (_type == "marksman")||(_type == "B_Soldier_M_F")||(_type == "O_Soldier_M_F");
_isAutorifleman = (_type == "mg")||(_type == "B_Soldier_AR_F")||(_type == "O_Soldier_AR_F");
_isAutoriflemanAsst = (_type == "mgasst")||(_type == "B_Soldier_AAR_F")||(_type == "O_Soldier_AAR_F");
_isLifeSaver = (_type == "medic")||(_type == "B_medic_F")||(_type == "O_medic_F");
_isGrenadier = (_type == "grenadier")||(_type == "B_Soldier_GL_F")||(_type == "O_Soldier_GL_F");
_isHelicopterPilot = (_type == "helipilot")||(_type == "B_HeliPilot_F")||(_type == "O_HeliPilot_F");
_isHelicopterCrew = (_type == "helicrew")||(_type == "B_HeliCrew_F")||(_type == "O_HeliCrew_F");
_isEngineer = (_type == "engineer")||(_type == "B_Engineer_F")||(_type == "B_Soldier_repair_F")||(_type == "O_Engineer_F")||(_type == "O_Soldier_repair_F");
_isCrewman = (_type == "crew")||(_type == "B_Crew_F")||(_type == "O_Crew_F");
_isPilot = (_type == "pilot")||(_type == "B_Pilot_F")||(_type == "O_Pilot_F");
_isRTO = (_type == "RTO")||(_type == "JTAC")||(_type == "B_Recon_JTAC_F")||(_type == "O_Recon_JTAC_F");
_isReconLeader = (_type == "reconleader")||(_type == "B_Recon_TL_F")||(_type == "O_Recon_TL_F");
_isReconMarksman = (_type == "RECONMARKSMAN")||(_type == "B_Recon_M_F")||(_type == "B_Recon_Sharpshooter_F")||(_type == "O_Recon_M_F")||(_type == "O_Pathfinder_F");
_isRecon = (_type == "recon")||(_type == "B_Recon_F")||(_type == "O_Recon_F");
_isReconDemo = (_type == "recondemo")||(_type == "B_Recon_exp_F")||(_type == "O_Recon_exp_F");
_isReconMedic = (_type == "reconmedic")||(_type == "B_Recon_Medic_F")||(_type == "O_Recon_Medic_F");
_isDemo = (_type == "demo")||(_type == "B_Soldier_exp_F")||(_type == "O_Soldier_exp_F");
_isHMG = (_type == "hmg")||(_type == "B_support_MG_F")||(_type == "O_support_MG_F");
_isStaticAT = (_type == "staticAT");
_isUAVOperator = (_type == "uav")||(_type == "B_Soldier_UAV_F")||(_type == "O_Soldier_UAV_F");
_isTripod = (_type == "tripod")||(_type == "B_support_AMG_F")||(_type == "O_support_AMG_F");
_isMortar = (_type == "mortar") || (_type == "B_support_Mort_F")||(_type == "O_support_Mort_F");
_isMortarAssistant = (_type == "mortarasst") || (_type == "B_support_AMort_F")||(_type == "O_support_AMort_F");
_isHeavyAT = (_type == "hat")||(_type == "B_Soldier_AT_F")||(_type == "O_Soldier_AT_F");
_isATAssistant = (_type == "hatast")||(_type == "B_Soldier_AAT_F")||(_type == "O_Soldier_AAT_F");
_isAA = (_type == "AA")||(_type == "B_Soldier_AA_F")||(_type == "O_Soldier_AA_F");
_isAAAssistant = (_type == "AAAST")||(_type == "B_Soldier_AAA_F")||(_type == "O_Soldier_AAA_F");
_isSniper = (_type == "sniper")||(_type == "B_Sniper_F")||(_type == "O_Sniper_F");
_isSpotter = (_type == "spotter")||(_type == "B_Spotter_F")||(_type == "O_Spotter_F");
_isMMG = (_type == "mmg")||(_type == "B_HeavyGunner_F")||(_type == "O_HeavyGunner_F");
_isMMGAsst = (_type == "mmgasst")||(_type == "Ammo Bearer");
_isViperLeader = (_type == "O_V_Soldier_TL_hex_F");
_isViperJTAC = (_type == "O_V_Soldier_JTAC_hex_F");
_isViperDemo = (_type == "O_V_Soldier_exp_hex_F");
_isViperMedic = (_type == "O_V_Soldier_Medic_hex_F");
_isViperMarksman = (_type == "O_V_Soldier_M_hex_F");
_isViperAT = (_type == "O_V_Soldier_LAT_hex_F");
