if !(isServer) exitWith {};

_veh = _this select 0;
_unit = driver _veh;

_shooterPos = getPosASL shooter1;
_crewRPos = getPosASL crewR1;
_crewLPos = getPosASL crewL1;
_crewFPos = getPosASL crewF1;
shooter1 playMoveNow "Acts_JetsShooterNavigate_stop_m";
sleep 2;
shooter1 playMoveNow "Acts_JetsShooterNavigate_stop_m";
crewL1 playMoveNow "Acts_JetsCrewaidLCrouch_loop_m";
sleep 0.5;
crewR1 playMoveNow "Acts_JetsCrewaidRCrouch_loop_m";
sleep 0.5;
crewF1 playMoveNow "Acts_JetsCrewaidF_runB_m";
sleep 0.5;
shooter1 playMove "Acts_JetsShooterIdle_m";
shooter1 playMoveNow "Acts_JetsShooterIdleMoveaway_loop_m";
sleep 4.7;
shooter1 playMove "Acts_JetsShooterIdleMoveaway_out_m";
sleep 3;
_unit setVariable ["prx_canLaunch", true, true];
waitUntil {_unit getVariable ["prx_isLaunching", false]};
crewF1 playMoveNow "Acts_JetsCrewaidFCrouch_loop_m";
sleep 1;
shooter1 playMove "Acts_JetsShooterShootingReady_loop_m";
sleep 3;
crewL1 playMoveNow "Acts_JetsCrewaidLCrouchThumbup_loop_m";
sleep 2;
crewR1 playMoveNow "Acts_JetsCrewaidRCrouchThumbup_loop_m";
sleep 2;
crewF1 playMoveNow "Acts_JetsCrewaidFCrouchThumbup_loop_m";
sleep 2;
shooter1 playMoveNow "Acts_JetsShooterShootingReady_pointing_m";
shooter1 playMove "Acts_JetsShooterShootingLaunch_loop_m";
waitUntil {launch1};
sleep 10;
[shooter1, "Acts_JetsShooterIdle_m"] remoteExec ["switchMove", 0];
[crewF1, "Acts_JetsCrewaidF_idle_m"] remoteExec ["switchMove", 0];
[crewL1, "Acts_JetsCrewaidL_idle_m"] remoteExec ["switchMove", 0];
[crewR1, "Acts_JetsCrewaidR_idle_m"] remoteExec ["switchMove", 0];
sleep 10;
shooter1 setPosASL _shooterPos;
crewR1 setPosASL _crewRPos;
crewL1 setPosASL _crewLPos;
crewF1 setPosASL _crewFPos;
_unit setVariable ["prx_canLaunch", false, true];
