if !(isServer) exitWith {};

_veh = _this select 0;
_unit = driver _veh;

_shooterPos = getPosASL shooter2;
_crewRPos = getPosASL crewR2;
_crewLPos = getPosASL crewL2;
_crewFPos = getPosASL crewF2;
shooter2 playMoveNow "Acts_JetsShooterNavigate_stop";
sleep 2;
shooter2 playMoveNow "Acts_JetsShooterNavigate_stop";
crewL2 playMoveNow "Acts_JetsCrewaidLCrouch_loop";
sleep 0.5;
crewR2 playMoveNow "Acts_JetsCrewaidRCrouch_loop";
sleep 0.5;
crewF2 playMoveNow "Acts_JetsCrewaidF_runB";
sleep 0.5;
shooter2 playMove "Acts_JetsShooterIdle_m";
shooter2 playMoveNow "Acts_JetsShooterIdleMoveaway_loop";
sleep 4.7;
shooter2 playMove "Acts_JetsShooterIdleMoveaway_out";
sleep 3;
_unit setVariable ["prx_canLaunch", true, true];
waitUntil {_unit getVariable ["prx_isLaunching", false]};
crewF2 playMoveNow "Acts_JetsCrewaidFCrouch_loop";
sleep 1;
shooter2 playMove "Acts_JetsShooterShootingReady_loop";
sleep 3;
crewL2 playMoveNow "Acts_JetsCrewaidLCrouchThumbup_loop";
sleep 2;
crewR2 playMoveNow "Acts_JetsCrewaidRCrouchThumbup_loop";
sleep 2;
crewF2 playMoveNow "Acts_JetsCrewaidFCrouchThumbup_loop";
sleep 2;
shooter2 playMoveNow "Acts_JetsShooterShootingReady_pointing";
shooter2 playMove "Acts_JetsShooterShootingLaunch_loop";
waitUntil {launch2};
sleep 10;
[shooter2, "Acts_JetsShooterIdle"] remoteExec ["switchMove", 0];
[crewF2, "Acts_JetsCrewaidF_idle"] remoteExec ["switchMove", 0];
[crewL2, "Acts_JetsCrewaidL_idle"] remoteExec ["switchMove", 0];
[crewR2, "Acts_JetsCrewaidR_idle"] remoteExec ["switchMove", 0];
sleep 10;
shooter2 setPosASL _shooterPos;
crewR2 setPosASL _crewRPos;
crewL2 setPosASL _crewLPos;
crewF2 setPosASL _crewFPos;
_unit setVariable ["prx_canLaunch", false, true];
